To each of our awslogs configs added awslogs-datetime-format: \[%Y-%m-%d…

diff --git a/src/services/connector/serverless.yml b/src/services/connector/serverless.yml
--- a/src/services/connector/serverless.yml
+++ b/src/services/connector/serverless.yml
@@ -62,7 +62,7 @@ custom:
       deploy:finalize: |
         set -e
         call=`aws lambda invoke --region ${self:provider.region} --function-name ${self:service}-${sls:stage}-configureConnectors --invocation-type RequestResponse --log Tail /dev/stdout`
-        if ! echo $call | jq '.FunctionError'; then 
+        if ! echo $call | jq '.FunctionError'; then
           echo "The Lambda function did not succeed." && exit 1;
         fi
     commands:
@@ -74,7 +74,7 @@ custom:
           echo """
           To conect to the connector, run:
           aws --region ${self:provider.region} ecs execute-command --cluster ${self:service}-${sls:stage}-connect --task ${task##*/} --container connect --interactive --command "/bin/sh"
-            
+
           To connect to the sql instantclient, run:
           aws --region ${self:provider.region} ecs execute-command --cluster ${self:service}-${sls:stage}-connect --task ${task##*/} --container instantclient --interactive --command "/bin/sh"
           """
@@ -245,6 +245,7 @@ resources:
                 awslogs-region: !Sub "${AWS::Region}"
                 awslogs-group: !Sub "${KafkaConnectWorkerLogGroup}"
                 awslogs-stream-prefix: fargate
+                awslogs-datetime-format: \[%Y-%m-%d %H:%M:%S,
           - Name: instantclient
             Image: "ghcr.io/oracle/oraclelinux8-instantclient:21"
             Memory: 2048 # This will kill the instantclient container if it goes over 2048, to preserve the connector container.
